model:
  model_name: "openai/deepseek-chat"
  model_kwargs:
    custom_llm_provider: "openai"
    api_base: "https://aihubmix.com/v1"
    drop_params: true
    temperature: 0.0
    parallel_tool_calls: true
  cost_tracking: "default"
